### PR TITLE
Single product page

### PR DESCRIPTION
**Pull request by msdeshmukh009**
product-page

### CODE REVIEW

**Review by suryxks — APPROVED** [review]
good to go

**Review by siddhigate — APPROVED** [review]
Code is very well structured! Product page looks good.
- You can consider using a utility class for width:100%.
- You can try to increase the size of these icons. The entire product page looks nice. Just a small tweaking in the alignment and font sizes here will make it look even better. Just a suggestion
image

**Review by gopalbbharadva — APPROVED** [review]
Great work Mahesh :)

**Comment by msdeshmukh009** [comment]
> Code is very well structured!
> 
> * You can consider using a utility class for width:100%.
> * You can try to increase the size of these icons. The entire product page looks nice. Just a small tweaking in the alignment and font sizes here will make it look even better. Just a suggestion
>   image

Thanks for pointing it out. I was bit careless there, made the changes accordingly.

**Pull request merged**
